#! /bin/bash


[[ "$#" -ne 1 ]] && echo "Illegal number of parameters." && exit 1

PATTERN=$1

grepfind() 
{
	for FILE in $(ls)
	do
		if [[ -d ${FILE} ]]
		then
			cd ${FILE}; grepfind; cd ..
	
		elif [[ $(cat ${FILE} | grep ${PATTERN}) ]]
		then
			printf '%s/%s\n' $(pwd) ${FILE}
		else
			continue
		fi
	done
}

grepfind
