#! /bin/bash


IGNORE=
while getopts "i:" OPT
do
    case $OPT in
        i)
          IGNORE=$OPTARG
	  shift 2
          ;;
    esac
done
if [[ ! -z ${IGNORE} ]]
then
	echo "Ignoring ${IGNORE}" 1>&2
fi


[[ "$#" -lt 1 ]] && echo "Illegal number of parameters." && exit 1

PATTERN=$1

grepfind() 
{
	for FILE in $(ls)
	do
		if [[ ${FILE} = ${IGNORE} ]]
		then
			continue
			
		elif [[ -d ${FILE} ]]
		then
			cd ${FILE}; grepfind; cd ..
	
		elif [[ $(cat ${FILE} | grep ${PATTERN}) ]]
		then
			printf '%s/%s\n' $(pwd) ${FILE}
		else
			continue
		fi
	done
}

grepfind
