#! /bin/bash

read a

for ((i=0; i<=15; i++))
do
    let b=a**2
    let a=$(echo $b | mawk '{OFS="";FS=""} {print substr($0,(length($0)/2),3)}')
    if [[ $a == 0* ]]; then
        echo $a
        a=$(seq $a $a)
        echo $a
    else
	echo $a
    fi
done
echo
