#! /usr/bin/env python3

import argparse
from quickumls import QuickUMLS


"""
A simple command line tool to run quickumls.
"""

QUICKUMLS_FP = "/Users/vasil024/tools/QuickUMLS/PreferredTermRankedInstall"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("text", type=str,
                        help="The text to search.")
    return parser.parse_args()


def pretty_print_result(result_json):
    cui = result_json["cui"]
    score = result_json["similarity"]
    semtypes = result_json["semtypes"]
    name = result_json["term"]
    try:
        name = result_json["preferred_term"]
    except KeyError:
        pass
    print(f"  {score:.2f}   {cui}:{name} {list(semtypes)}")


def main(text):
    quick = QuickUMLS(QUICKUMLS_FP)
    return quick.match(text)


if __name__ == "__main__":
    args = parse_args()
    phrases = main(args.text)
    for (i, phrase) in enumerate(phrases):
        print(f"Phrase {phrase[0]['ngram']}")
        for res in phrase:
            pretty_print_result(res)
