#! /bin/bash

# A simple cli tool for mounting a usb or other removable media.

if [ $# != 1 ] 
    then
	echo "Usage: mntusb <mount_point>" 1>&2
	exit 1
fi

mnt_pnt="$1"

LABELS=$(ls -l /dev/disk/by-label | awk 'NR>1' | awk '{print $9}')
DEVICES=$(ls -l /dev/disk/by-label | awk 'NR>1' | awk '{print $NF}' | tr -dc 'a-z1-9\n')
LABELS=($LABELS)
DEVICES=($DEVICES)

for ((i=0;i<${#DEVICES[@]};i++))
do
	grep ${DEVICES[$i]} /proc/mounts > /dev/null || \
		echo "$i) ${DEVICES[$i]} ${LABELS[$i]}"
done

echo -n "? "
read id
if [ $id = "" ] || [ ${#DEVICES[@]} =~ $id ]; then
	echo $id not valid. Nothing mounted.
	exit 0
else
	mount -o umask=0000 /dev/${DEVICES[$id]} $mnt_pnt && exit 0
fi
