#! /bin/bash

# A simple cli tool for unmounting removable media.

if [ $# -gt 0 ]; then
	echo "Usage: umntusb"
	exit 1
fi

LABELS=$(ls -l /dev/disk/by-label | awk 'NR>1' | awk '{print $9}')
DEVICES=$(ls -l /dev/disk/by-label | awk 'NR>1' | awk -F/ '{print $NF}')
LABELS=($LABELS)
DEVICES=($DEVICES)

for ((i=0;i<${#DEVICES[@]};i++))
do
	grep ${DEVICES[$i]} /proc/mounts > /dev/null && \
		echo "$i) ${DEVICES[$i]} ${LABELS[$i]}"
done

echo -n "? "
read id
if [[ $id = "" ]]; then
	exit 0
else
	umount /dev/${DEVICES[$id]} && exit 0
fi
